#!/bin/sh
# Gradle wrapper script. The actual wrapper jar is generated by
# `gradle wrapper` on first invocation; this script is a minimal
# fallback that uses a system-installed gradle if the jar is missing.

DIR="$(cd "$(dirname "$0")" && pwd)"
APP_HOME="$DIR"

if [ -n "$JAVA_HOME" ]; then
    JAVACMD="$JAVA_HOME/bin/java"
else
    JAVACMD="java"
fi

if [ -f "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec "$JAVACMD" \
        -classpath "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" \
        org.gradle.wrapper.GradleWrapperMain "$@"
else
    echo "gradle-wrapper.jar not found; falling back to system gradle."
    exec gradle "$@"
fi
